config/routes.rb
Legend::Application.routes.draw do
  scope '(:locale)' do
    root :to => 'welcome#index'

    controller :crumb_sorter do
      get "crumbs-sorter/index"=>:index, as:"crumbs_sorter"
      post "crumbs-sorter/sort"=>:sort, as:"sort_crumbs_sorter"
    end

    devise_for :users

    resources :messages do
      member do
        post "ignore"=>:ignore
      end
    end

    resources :stories do
      member do
        get "writers"=>:writers
        post "writers"=>:update_writers
      end
      resources :events
    end

    resources :events,:only=>:none do 
      resources :crumbs,only: [:edit,:update,:destroy] do 
        collection do 
          get 'upload'
          post 'upload',:to=>:upload_one
        end
      end
    end

    get "/paperclip/:class/:attachment/:id/:style/:filename",to:"assets#show"

    get "welcome/index"
  end
end

app/controllers/crumb_sorter_controller.rb
class CrumbSorterController < ApplicationController
	before_action :upload_shot
  def index
  	@crumbs=current_user.tmp_event.crumbs
  	@album=current_story.events.ready.map{|e| [e.start_date.to_s+" "+e.caption,e.id]}
  end

  def sort
  	@event=current_story.events.find params[:event_id]
  	Crumb.transaction do
  		@event.crumbs<<current_user.tmp_event.crumbs
  	end
  	redirect_to [current_story,@event]
  end

  private
  def upload_shot
    if current_user.tmp_event.crumbs.empty?
      render "/crumb_sorter/empty"
    end
  end
end

app/helpers/crumb_sorter_helper.rb
module CrumbSorterHelper
end

app/views/crumb_sorter/empty.html.erb
<h3><%= t('.no_upload') %></h3>

app/views/crumb_sorter/index.html.erb
<h1><%=t('.choose_event')%></h1>

<% unless @album.empty? %>
	<%= form_tag sort_crumbs_sorter_path  do %>
	  <%= select_tag "event_id",options_for_select(@album) %>
	  <%= submit_tag t('.ok'),class:"btn btn-primary" %>
	  <span> <%=t('.or')%> </span>
	  <%= link_to t('.create_new_event'),new_story_event_path(current_story), class:"btn btn-success" %>
	<% end %>
<% else %>
	<%= link_to t('.create_new_event'),new_story_event_path(current_story), class:"btn btn-success" %>
<% end %>
<ul class="thumbnails">
	<% @crumbs.each do |crumb| %>
		<li class="span1">
			<div class="thumbnail">
		    <%= image_tag crumb.media.url(:square) %>
			</div>
  		</li>
	<% end %>
</ul>