config/routes.rb
Legend::Application.routes.draw do
  scope '(:locale)' do
    root :to => 'welcome#index'

    controller :crumb_sorter do
      get "crumbs-sorter/index"=>:index, as:"crumbs_sorter"
      post "crumbs-sorter/sort"=>:sort, as:"sort_crumbs_sorter"
    end

    devise_for :users

    resources :messages do
      member do
        post "ignore"=>:ignore
      end
    end

    resources :stories do
      member do
        get "writers"=>:writers
        post "writers"=>:update_writers
      end
      resources :events
    end

    resources :events,:only=>:none do 
      resources :crumbs,only: [:edit,:update,:destroy] do 
        collection do 
          get 'upload'
          post 'upload',:to=>:upload_one
        end
      end
    end

    get "/paperclip/:class/:attachment/:id/:style/:filename",to:"assets#show"

    get "welcome/index"
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  belongs_to :story
  belongs_to :cover, :class_name=>'Crumb',:foreign_key => "crumb_id"
  has_many :crumbs,:dependent=>:destroy, :after_add=>:crumb_added

  validates :caption,:start_date,:duration,:presence=>true
  validates_numericality_of :duration, greater_than: 0

  scope :ready, -> {where(:available=>true)}

  include Rails.application.routes.url_helpers

  def to_timeline
    cover.caption||=""
    cover.description||="<a href='"+cover.media.url(:original)+"'>view</a>"
  	date={
  		"startDate"=>start_date.to_s.gsub(/-/,','),
  		"endDate"=>(start_date+duration).to_s.gsub(/-/,','),
  		"headline"=>"<a href='"+(id.nil? ? '#' : story_event_path(self.story,self))+"'>"+caption+"</a>",
  		"text"=>description,
  		"tag"=>"sweet"<<(id.nil? ? '0' : (id%3).to_s),
  		"asset"=>{
  			"media"=>cover.media.url(:middle),
  			"thumbnail"=>cover.media.url(:small),
  			"credit"=>cover.description,
  			"caption"=>cover.caption
  		}
  	}
  	era=date.select{|k| ["startDate","endDate","tag"].include? k}
  	{"date"=>date,"era"=>era}
  end

  def self.empty_event
    c=Crumb.new(caption:"",description:"")
    c.media.instance_eval do
      def url(style)
        "/assets/no_events.jpg"
      end
    end
    Event.new(start_date:Date.today,
      duration:1,
      caption:"No more events",
      description:"",
      available:false,
      cover:c
      )
  end

  def crumb_added(crumb)
    unless cover
      self.cover=crumb
      self.save
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_story
  
  # GET /events
  # GET /events.json
  def index
    @events = @story.events.ready.page(params[:page]).per(30)
    @page=params[:page]

    respond_to do |format|
      format.html 
      format.json{ render json: @story.timeline(@events) }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = @story.events.find(params[:id])
    params[:mode]="book" unless ["book","slide","wall"].include? params[:mode]
    @mode="show_"<<params[:mode]

    respond_to do |format|
      format.html { render @mode }
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = @story.events.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = @story.events.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = @story.events.build(event_params)
    @event.user=current_user
    saved=false

    Event.transaction do
      saved=@event.save
      @event.crumbs<<current_user.tmp_event.crumbs
    end

    respond_to do |format|
      if saved
        format.html { redirect_to [@story,@event], notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = @story.events.find(params[:id])

    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to [@story,@event], notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = @story.events.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to story_events_path(@story) }
      format.json { head :no_content }
    end
  end

  private 
    def find_story
      @story=current_user.stories.find params[:story_id]
      current_story_set @story
      redirect_to new_story_path unless @story
    end

    def event_params
      params.require(:event).permit(:caption, :description, :duration, :start_date)
    end
  
end

app/helpers/events_helper.rb
module EventsHelper
	def tmp_crumbs
		current_user.tmp_event.crumbs
	end
end

app/views/events/_form.html.erb
<%= form_for([@story,@event]) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> <%=t('.prohibite_save_event')%></h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :caption %><br />
    <%= f.text_field :caption %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description,rows:4 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1><%= t('.edit_event')</h1>

<%= render 'form' %>

<%= link_to 'Show', [@story,@event] %> |
<%= link_to 'Back', story_events_path(@story) %>

app/views/events/index.html.erb
<div id="time_line">
</div>

<p>
  <%= paginate @events %>
</p>
<p>
<%=  link_to t('.add_event'), upload_event_crumbs_path(current_user.tmp_event),class:"btn btn-large btn-info" %>
</p>

<script type="text/javascript">
 $(document).ready(function() {
  var dataObject = <%= raw @story.timeline(@events).to_json %>
    createStoryJS({
      type: 'timeline',
      width: '100%',
      height: '700',
      source: dataObject,
      embed_id: 'time_line',
      lang: '/assets/application.js',
      js: '/assets/application.js',
      css: '/assets/application.css'
    });
  });
</script>

app/views/events/new.html.erb
<div class="row">
  <div class="span6 offset3"><h1><%=t('.new_event')%></h1></div>
</div>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span5">
      <%= render 'form' %>
    </div>
    <div class="span7">
      <ul class="thumbnails">
		<% tmp_crumbs.each do |crumb| %>
			<li class="span4">
				<div class="thumbnail">
			    <%= image_tag crumb.media.url(:square),size:"100x100" %>
				</div>
	  		</li>
		<% end %>
	  </ul>
    </div>
  </div>
</div>

<%= link_to t('.back'), story_events_path(@story) %>

app/views/events/show_book.html.erb
<h1><%=@event.caption%></h1>
<p><%=@event.description%></p>

<%= link_to_modal "<i class='icon-pencil'></i>".html_safe<<t('.edit'),edit_story_event_path(@story,@event),class:"btn btn-info"%>
<%= link_to "<i class='icon-trash'></i> ".html_safe<<t('.destroy_book'), story_event_path(@story,@event),:confirm => t('.r_u_sure'),method:"delete",class:"btn btn-danger" %>
<%= link_to "<i class='icon-book'></i> ".html_safe<<t('.slides'), story_event_path(@story,@event,mode:"slide"),class:"btn btn-primary" %> 
<%= link_to t('.back'), story_events_path(@story),class:"btn btn-info" %>

<div class="book_wrapper">
			<a id="next_page_button"></a>
			<a id="prev_page_button"></a>
			<div id="loading" class="loading"><%=t('.loading_pages')%></div>
			<div id="mybook" style="display:none;">
				<div class="b-load">
					<% @event.crumbs.each do |crumb| %>
						<div>
							<%= image_tag(crumb.media.url(:book))%>
							<h1 class="crumb_<%=crumb.id%>"><%= crumb.caption %></h1>
							<p class="book_text crumb_<%=crumb.id%>"><%= crumb.description %></p>
							<%= link_to_modal "<i class='icon-pencil'></i>".html_safe<<t('.edit'),edit_event_crumb_path(@event,crumb),class:"article"%>
							<%= link_to "<i class='icon-trash'></i> ".html_safe<<t('.delete'),event_crumb_path(@event,crumb),:method=>"delete",:confirm=>t('.r_u_sure'),class:"demo" %> 
						</div>
					<% end %>
				</div>
			</div>
</div>

<script type="text/javascript">
			Cufon.replace('.book_wrapper a', {hover:true});
			Cufon.replace('.title', {textShadow: '1px 1px #C59471', fontFamily:'ChunkFive'});
			Cufon.replace('.reference a', {textShadow: '1px 1px #C59471', fontFamily:'ChunkFive'});
			Cufon.replace('.loading', {textShadow: '1px 1px #000', fontFamily:'ChunkFive'});
</script>
<script type="text/javascript">
			$(function() {
				var $mybook 		= $('#mybook');
				var $bttn_next		= $('#next_page_button');
				var $bttn_prev		= $('#prev_page_button');
				var $loading		= $('#loading');
				var $mybook_images	= $mybook.find('img');
				var cnt_images		= $mybook_images.length;
				var loaded			= 0;
				//preload all the images in the book,
				//and then call the booklet plugin

				$mybook_images.each(function(){
					var $img 	= $(this);
					var source	= $img.attr('src');
					$('<img/>').load(function(){
						++loaded;
						if(loaded == cnt_images){
							$loading.hide();
							$bttn_next.show();
							$bttn_prev.show();
							$mybook.show().booklet({
								name:               null,                            // name of the booklet to display in the document title bar
								width:              800,                             // container width
								height:             500,                             // container height
								speed:              600,                             // speed of the transition between pages
								direction:          'LTR',                           // direction of the overall content organization, default LTR, left to right, can be RTL for languages which read right to left
								startingPage:       0,                               // index of the first page to be displayed
								easing:             'easeInOutQuad',                 // easing method for complete transition
								easeIn:             'easeInQuad',                    // easing method for first half of transition
								easeOut:            'easeOutQuad',                   // easing method for second half of transition

								closed:             true,                           // start with the book "closed", will add empty pages to beginning and end of book
								closedFrontTitle:   null,                            // used with "closed", "menu" and "pageSelector", determines title of blank starting page
								closedFrontChapter: null,                            // used with "closed", "menu" and "chapterSelector", determines chapter name of blank starting page
								closedBackTitle:    null,                            // used with "closed", "menu" and "pageSelector", determines chapter name of blank ending page
								closedBackChapter:  null,                            // used with "closed", "menu" and "chapterSelector", determines chapter name of blank ending page
								covers:             false,                           // used with  "closed", makes first and last pages into covers, without page numbers (if enabled)

								pagePadding:        10,                              // padding for each page wrapper
								pageNumbers:        true,                            // display page numbers on each page

								hovers:             false,                            // enables preview pageturn hover animation, shows a small preview of previous or next page on hover
								overlays:           false,                            // enables navigation using a page sized overlay, when enabled links inside the content will not be clickable
								tabs:               false,                           // adds tabs along the top of the pages
								tabWidth:           60,                              // set the width of the tabs
								tabHeight:          20,                              // set the height of the tabs
								arrows:             false,                           // adds arrows overlayed over the book edges
								cursor:             'pointer',                       // cursor css setting for side bar areas

								hash:               false,                           // enables navigation using a hash string, ex: #/page/1 for page 1, will affect all booklets with 'hash' enabled
								keyboard:           true,                            // enables navigation with arrow keys (left: previous, right: next)
								next:               $bttn_next,          			// selector for element to use as click trigger for next page
								prev:               $bttn_prev,          			// selector for element to use as click trigger for previous page

								menu:               null,                            // selector for element to use as the menu area, required for 'pageSelector'
								pageSelector:       false,                           // enables navigation with a dropdown menu of pages, requires 'menu'
								chapterSelector:    false,                           // enables navigation with a dropdown menu of chapters, determined by the "rel" attribute, requires 'menu'

								shadows:            true,                            // display shadows on page animations
								shadowTopFwdWidth:  166,                             // shadow width for top forward anim
								shadowTopBackWidth: 166,                             // shadow width for top back anim
								shadowBtmWidth:     50,                              // shadow width for bottom shadow

								before:             function(){},                    // callback invoked before each page turn animation
								after:              function(){}                     // callback invoked after each page turn animation
							});
							Cufon.refresh();
						}
					}).attr('src',source);
				});
				
			});
        </script>

app/views/events/show_slide.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
      <h4><%=@event.caption%></h4>
      <h7><%=@event.description%></h7>


    </div>
    <div class="span10">
      <div id='gallery'>
		<% @event.crumbs.each do |crumb| %>
		  <%=link_to image_tag(crumb.media.url(:square)),crumb.media.url(:original)%>
		<% end %>
	  </div>
    </div>
  </div>
</div>

<%= link_to "<i class='icon-book'></i>".html_safe<<t('.return_2_book'), story_event_path(@story,@event,mode:"book"),class:"btn btn-info" %>  
<%= link_to t('.back'), story_events_path(@story),class:"btn btn-info" %>
	  
<script type="text/javascript">
	$('#gallery').photobox('a');
			// or with a fancier selector and some settings, and a callback:
	$('#gallery').photobox('a:first', { thumbs:true, time:0 }, imageLoaded);
	function imageLoaded(){
		console.log('image has been loaded...');
	}
</script>

app/views/events/show_wall.html.erb
<!-- not use this view -->
<p id="notice"><%= notice %></p>
<h1><%=@event.caption%></h1>
<p><%=@event.description%></p>
<%= link_to "<i class='icon-book'></i> Slides".html_safe, story_event_path(@story,@event,mode:"slide"),class:"act" %> 
<%= link_to "<i class='icon-trash'></i> Destroy".html_safe, story_event_path(@story,@event),:confirm => "Are you sure?",method:"delete",class:"act" %>

<div class="empty">
	<div class="photowall">
	    	<% @event.crumbs.each do |crumb| %>
	    	<div class="pw-slide">
	    		<%= image_tag(crumb.media.url(:middle),class:"pw-image")%>
		        <div class="pw-image-desc">
		            <h1 class="crumb_<%=crumb.id%>"><%= crumb.caption %></h1>
					<p class="crumb_<%=crumb.id%>"><%= crumb.description %></p>
					<p><%= link_to_modal "<i class='icon-pencil'></i>Edit".html_safe,edit_event_crumb_path(@event,crumb)%></p>
					<div>
		        	  <!-- nothing now! -->
		        	</div>
		        </div>
	    	</div>
	        <% end %>
	</div>
</div>
<br/>

<script type="text/javascript">
	$(document).ready(function(){
	  $(".photowall").photoWall();
	});
</script>