config/routes.rb
Legend::Application.routes.draw do
  scope '(:locale)' do
    root :to => 'welcome#index'

    controller :crumb_sorter do
      get "crumbs-sorter/index"=>:index, as:"crumbs_sorter"
      post "crumbs-sorter/sort"=>:sort, as:"sort_crumbs_sorter"
    end

    devise_for :users

    resources :messages do
      member do
        post "ignore"=>:ignore
      end
    end

    resources :stories do
      member do
        get "writers"=>:writers
        post "writers"=>:update_writers
      end
      resources :events
    end

    resources :events,:only=>:none do 
      resources :crumbs,only: [:edit,:update,:destroy] do 
        collection do 
          get 'upload'
          post 'upload',:to=>:upload_one
        end
      end
    end

    get "/paperclip/:class/:attachment/:id/:style/:filename",to:"assets#show"

    get "welcome/index"
  end
end

app/models/story.rb
class Story < ActiveRecord::Base
  
  has_attached_file :cover,
  :styles=>{:middle=>"400x400>",:small=>"32x32",:square=>"200x300#"}, 
  :convert_options=>{
    :middle=>"-quality 75 -strip",
    :square=>"-quality 75 -strip",
    :small=>"-quality 75 -strip"
  },
  :path => ":rails_root/paperclip/:class/:attachment/:id/:style/:filename",
  :url => "/paperclip/:class/:attachment/:id/:style/:filename"
  validates :instruction,:presence=>true
  validates :title,:presence=>true
  validates_attachment :cover, :presence => true
  validates_format_of :cover_content_type, :with => /\Aimage/

  has_many :users_info,class_name:"StoryInfo",foreign_key:"story_id",:dependent=>:destroy
  has_many :users,:through=>:users_info
  has_many :events,:dependent=>:destroy

  def timeline(events)
    date_list=[]
    era_list=[]
    events<<Event.empty_event if events.size==0
    events.each do |e|
      tl=e.to_timeline
      date_list<<tl["date"]
      era_list<<tl["era"]
    end
    
    {
      "timeline"=>{
        "headline"=>title,
        "type"=>"default",
        "text"=>instruction,
        "asset"=>{
          "media"=>cover.url(:middle),
          "credit"=>"",
          "caption"=>""
        },
        "date"=>date_list,
        "era"=>era_list
      }
    }
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    @stories=current_user.stories
    respond_to do |format|
      if @stories.empty?
        format.html { redirect_to new_story_path,notice:"Please create your story first!"}
      elsif @stories.size==1
        format.html { redirect_to story_path(@stories.first) }
      else
        format.html
      end
    end
  end

  def create
    @story=Story.new(story_params)
    created=true
    Story.transaction do
      begin
        @story.save!
        current_user.stories<<@story
        current_story=@story
      rescue Exception => e
        created=false
        raise ActiveRecord::Rollback
      end
    end
    if created
      redirect_to @story, notice: 'Story was successfully created.'
    else
      render action: "new"
    end
  end

  def new
    @story=Story.new
  end

  def show
    @story=current_user.stories.find params[:id]
  end

  def edit
    @story=current_user.stories.find params[:id]
  end

  def update
    @story=current_user.stories.find params[:id]
    if @story.update(story_params)
        redirect_to @story, notice: 'story was successfully updated.'
      else
        render action: "edit"
    end
  end

  def destroy
    @story=current_user.stories.find params[:id]
    @story.destroy
    redirect_to stories_url
  end

  def writers
    @story=current_user.stories.find params[:id]
    @honey=@story.users.reject{|x| x==current_user}.first
  end

  def update_writers
    @story=current_user.stories.find params[:id]
    @users=User.where.not(:id=>current_user.id).
      where("email like ? or nickname like ?","%#{params[:writer_id]}%","%#{params[:writer_id]}%").limit(10)
    
    respond_to do |format|
      format.js
    end
  end

  private
    def story_params
      params.require(:story).permit(:cover, :end_date, :instruction, :start_date, :title)
    end

end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= form_for(@story,html: {multipart:true, class:"form-horizontal" }) do |f| %>

  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> <%=t('.prohibite_save_story')%></h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <fieldset> 
  <div class="control-group">
    <%= f.label :title,class:"control-label" %>
    <div class="controls">
      <%= f.text_field :title, placeholder:"Title" %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <div class="fileupload fileupload-new" data-provides="fileupload">
        <div class="fileupload-preview thumbnail" style="width: 200px; height: 150px;"></div>
        <div>
          <span class="btn btn-file"><span class="fileupload-new"><%=t('.select_image')%></span><span class="fileupload-exists"><%=t('.change')%></span><%= f.file_field :cover %></span>
          <a href="#" class="btn fileupload-exists" data-dismiss="fileupload"><%=t('.remove')%></a>
        </div>
      </div>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :instruction,class:"control-label" %>
    <div class="controls">
      <%= f.text_area :instruction, placeholder:"Description",rows:3 %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= f.submit nil,class: "btn btn-primary"%>
    </div>
  </div>
</fieldset>
<% end %>

<script type="text/javascript">
/* ===========================================================
 * bootstrap-fileupload.js j2
 * http://jasny.github.com/bootstrap/javascript.html#fileupload
 * ===========================================================
 * Copyright 2012 Jasny BV, Netherlands.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ========================================================== */

!function ($) {

  "use strict"; // jshint ;_

 /* FILEUPLOAD PUBLIC CLASS DEFINITION
  * ================================= */

  var Fileupload = function (element, options) {
    this.$element = $(element)
    this.type = this.$element.data('uploadtype') || (this.$element.find('.thumbnail').length > 0 ? "image" : "file")
      
    this.$input = this.$element.find(':file')
    if (this.$input.length === 0) return

    this.name = this.$input.attr('name') || options.name

    this.$hidden = this.$element.find('input[type=hidden][name="'+this.name+'"]')
    if (this.$hidden.length === 0) {
      this.$hidden = $('<input type="hidden" />')
      this.$element.prepend(this.$hidden)
    }

    this.$preview = this.$element.find('.fileupload-preview')
    var height = this.$preview.css('height')
    if (this.$preview.css('display') != 'inline' && height != '0px' && height != 'none') this.$preview.css('line-height', height)

    this.original = {
      'exists': this.$element.hasClass('fileupload-exists'),
      'preview': this.$preview.html(),
      'hiddenVal': this.$hidden.val()
    }
    
    this.$remove = this.$element.find('[data-dismiss="fileupload"]')

    this.$element.find('[data-trigger="fileupload"]').on('click.fileupload', $.proxy(this.trigger, this))

    this.listen()
  }
  
  Fileupload.prototype = {
    
    listen: function() {
      this.$input.on('change.fileupload', $.proxy(this.change, this))
      $(this.$input[0].form).on('reset.fileupload', $.proxy(this.reset, this))
      if (this.$remove) this.$remove.on('click.fileupload', $.proxy(this.clear, this))
    },
    
    change: function(e, invoked) {
      if (invoked === 'clear') return
      
      var file = e.target.files !== undefined ? e.target.files[0] : (e.target.value ? { name: e.target.value.replace(/^.+\\/, '') } : null)
      
      if (!file) {
        this.clear()
        return
      }
      
      this.$hidden.val('')
      this.$hidden.attr('name', '')
      this.$input.attr('name', this.name)

      if (this.type === "image" && this.$preview.length > 0 && (typeof file.type !== "undefined" ? file.type.match('image.*') : file.name.match(/\.(gif|png|jpe?g)$/i)) && typeof FileReader !== "undefined") {
        var reader = new FileReader()
        var preview = this.$preview
        var element = this.$element

        reader.onload = function(e) {
          preview.html('<img src="' + e.target.result + '" ' + (preview.css('max-height') != 'none' ? 'style="max-height: ' + preview.css('max-height') + ';"' : '') + ' />')
          element.addClass('fileupload-exists').removeClass('fileupload-new')
        }

        reader.readAsDataURL(file)
      } else {
        this.$preview.text(file.name)
        this.$element.addClass('fileupload-exists').removeClass('fileupload-new')
      }
    },

    clear: function(e) {
      this.$hidden.val('')
      this.$hidden.attr('name', this.name)
      this.$input.attr('name', '')

      //ie8+ doesn't support changing the value of input with type=file so clone instead
      if (navigator.userAgent.match(/msie/i)){ 
          var inputClone = this.$input.clone(true);
          this.$input.after(inputClone);
          this.$input.remove();
          this.$input = inputClone;
      }else{
          this.$input.val('')
      }

      this.$preview.html('')
      this.$element.addClass('fileupload-new').removeClass('fileupload-exists')

      if (e) {
        this.$input.trigger('change', [ 'clear' ])
        e.preventDefault()
      }
    },
    
    reset: function(e) {
      this.clear()
      
      this.$hidden.val(this.original.hiddenVal)
      this.$preview.html(this.original.preview)
      
      if (this.original.exists) this.$element.addClass('fileupload-exists').removeClass('fileupload-new')
       else this.$element.addClass('fileupload-new').removeClass('fileupload-exists')
    },
    
    trigger: function(e) {
      this.$input.trigger('click')
      e.preventDefault()
    }
  }

  
 /* FILEUPLOAD PLUGIN DEFINITION
  * =========================== */

  $.fn.fileupload = function (options) {
    return this.each(function () {
      var $this = $(this)
      , data = $this.data('fileupload')
      if (!data) $this.data('fileupload', (data = new Fileupload(this, options)))
      if (typeof options == 'string') data[options]()
    })
  }

  $.fn.fileupload.Constructor = Fileupload


 /* FILEUPLOAD DATA-API
  * ================== */

  $(document).on('click.fileupload.data-api', '[data-provides="fileupload"]', function (e) {
    var $this = $(this)
    if ($this.data('fileupload')) return
    $this.fileupload($this.data())
      
    var $target = $(e.target).closest('[data-dismiss="fileupload"],[data-trigger="fileupload"]');
    if ($target.length > 0) {
      $target.trigger('click.fileupload')
      e.preventDefault()
    }
  })

}(window.jQuery);

</script>

app/views/stories/edit.html.erb
<h1><%=t('.edit_cover')%></h1>
<%= render 'form' %>

app/views/stories/index.html.erb
<h1><%=t('.choice_book')%></h1>
<ul class="thumbnails">
  <% @stories.each do |story| %>
  <li class="span4">
    <div class="thumbnail">
      <%= link_to image_tag(story.cover.url(:middle)),story_events_path(story) %>
      <h3><%= story.title %></h3>
      <p>T<%= story.instruction %></p>
    </div>
  </li>
  <% end %>
</ul>

app/views/stories/new.html.erb
<h1><%=t('.create_our_story')%></h1>
<%= render 'form' %>

app/views/stories/show.html.erb
<div class="hero-unit">
	<div class="container-fluid">
	  <div class="row-fluid">
	    <div class="span5">
	      <%= image_tag @story.cover.url(:middle) %>
	    </div>
	    <div class="span7">
	      <h2><%= link_to @story.title,story_events_path(@story) %><h2>
	      	<% if @story.users.size==2 %>
	      	  <h5>Written by <%=@story.users.first.display_name%> and <%=@story.users.second.display_name%></h5>
	      	  <% end %>
	      <h5><%= @story.instruction %></h5>
	      <%= link_to_modal t('.writers_list'),writers_story_path(@story) %>
	    </div>
	  </div>
	</div>
</div>

<%= link_to t('.edit'), edit_story_path %> |
<%= link_to t('.open_book'), story_events_path(@story) %>

app/views/stories/update_writers.js.erb
$("#honey_list").html("");
<% @users.each do |user| %>
  $("#honey_list").append("<li><%= user.nickname||user.email %></li>");
<%end%>

app/views/stories/writers.html.erb
<h1><%=t('.set_honey_here')%></h1>
<%= form_tag writers_story_path(@story),remote:true  do %>
    <%= label_tag t(".honey") %>
	<%= text_field_tag :writer_id,@honey.nil? ? "" : (@honey.nickname||@honey.email) %>
	<%= submit_tag t('.ok'),class:"btn btn-primary" %>
<% end %>
<ul id="honey_list" >
  <li><a href="#">Action</a></li>
</ul>