config/routes.rb
Legend::Application.routes.draw do
  scope '(:locale)' do
    root :to => 'welcome#index'

    controller :crumb_sorter do
      get "crumbs-sorter/index"=>:index, as:"crumbs_sorter"
      post "crumbs-sorter/sort"=>:sort, as:"sort_crumbs_sorter"
    end

    devise_for :users

    resources :messages do
      member do
        post "ignore"=>:ignore
      end
    end

    resources :stories do
      member do
        get "writers"=>:writers
        post "writers"=>:update_writers
      end
      resources :events
    end

    resources :events,:only=>:none do 
      resources :crumbs,only: [:edit,:update,:destroy] do 
        collection do 
          get 'upload'
          post 'upload',:to=>:upload_one
        end
      end
    end

    get "/paperclip/:class/:attachment/:id/:style/:filename",to:"assets#show"

    get "welcome/index"
  end
end

app/models/crumb.rb
class Crumb < ActiveRecord::Base
  has_attached_file :media,
  :styles=>{:middle=>"500x500>",:small=>"32x32",:square=>"200x200#",:book=>"300x163#"}, 
  :convert_options=>{
    :middle=>"-quality 75 -strip",
    :small=>"-quality 75 -strip",
    :square=>"-quality 75 -strip",
    :book=>"-quality 75 -strip"
  },
  :path => ":rails_root/paperclip/:class/:attachment/:id/:style/:filename",
  :url => "/paperclip/:class/:attachment/:id/:style/:filename"
  validates_attachment :media, :presence => true
  validates_format_of :media_content_type, :with => /\Aimage/

  belongs_to :event

  include Rails.application.routes.url_helpers

  def to_jq_upload
    {
      "name" => read_attribute(:media_file_name),
      "size" => read_attribute(:media_file_size),
      "url" => media.url(:original),
      "delete_url" => event_crumb_path(self.event,self),
      "delete_type" => "DELETE" 
    }
  end
end

app/controllers/crumbs_controller.rb
class CrumbsController < ApplicationController
  before_action :find_event

  # GET /events/:event_id/crumbs/upload
  # GET /events/:event_id/crumbs/upload.json
  def upload
    @crumbs = @event.crumbs

    respond_to do |format|
      format.html # upload.html.erb
      format.json { render json: @crumbs.map{|crumb| crumb.to_jq_upload } }
    end
  end
  # POST /events/:event_id/crumbs/upload
  # POST /events/:event_id/crumbs/upload.json
  def upload_one
    @crumb = @event.crumbs.build(crumb_params)

    respond_to do |format|
      if @crumb.save
        format.html {  
          render :json => [@crumb.to_jq_upload].to_json,  
          :content_type => 'text/html',  
          :layout => false  
        }
        format.json { render json: {files: [@crumb.to_jq_upload]}, status: :created, location: [@event,@crumb]  }
      else
        format.html { render action: "new" }
        format.json { render json: @crumb.errors, status: :unprocessable_entity }
      end
    end
  end


  # GET /events/:event_id/crumbs/1/edit
  def edit
    @crumb = @event.crumbs.find(params[:id])
  end

  # PUT /events/:event_id/crumbs/1
  # PUT /events/:event_id/crumbs/1.json
  def update
    @crumb = @event.crumbs.find(params[:id])

    respond_to do |format|
      if @crumb.update(crumb_params)
        format.html { redirect_to @crumb, notice: 'Crumb was successfully updated.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @crumb.errors, status: :unprocessable_entity }
        format.js { head :no_content }
      end
    end
  end

  # DELETE /events/:event_id/crumbs/1
  # DELETE /events/:event_id/crumbs/1.json
  def destroy
    @crumb = @event.crumbs.find(params[:id])
    @crumb.destroy

    respond_to do |format|
      format.html { redirect_to [@event.story,@event] }
      format.json { head :no_content }
    end
  end

  private
    def find_event
      @event=Event.find params[:event_id]
    end
    def crumb_params
      params.require(:crumb).permit(:caption, :description, :media)
    end
end

app/helpers/crumbs_helper.rb
module CrumbsHelper
end

app/views/crumbs/_form.html.erb
<%= form_for([@event,@crumb],remote:true,html:{class:"form-horizontal"}) do |f| %>
  <% if @crumb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crumb.errors.count, "error") %> <%=t('.prohibite_save_crumb')%></h2>

      <ul>
      <% @crumb.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <legend><%=t('.update_detail')%></legend>
  <div class="control-group">
    <%= f.label :caption,class:"control-label" %>
    <div class="controls">
      <%= f.text_field :caption %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description,class:"control-label" %>
    <div class="controls">
      <%= f.text_area :description,rows:3 %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= f.submit t('.update'), class:"btn btn-primary"%>
    </div>
  </div>
<% end %>

app/views/crumbs/edit.html.erb
<%= render 'form' %>

app/views/crumbs/update.js.erb
$("h1.crumb_<%=@crumb.id%>").html("<%=@crumb.caption%>");
$("p.crumb_<%=@crumb.id%>").html("<%=@crumb.description%>");
$.modal.close();

app/views/crumbs/upload.html.erb
<div class="container">
  <h2><%=t('.upload_love_shot')%></h2>
  <%= form_for [@event,Crumb.new],url: upload_event_crumbs_path, :html => { :multipart => true, :id => "fileupload"  } do |f| %>
    <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
    <div class="row fileupload-buttonbar">
      <div class="span7">
        <!-- The fileinput-button span is used to style the file input field as button -->
        <span class="btn btn-success fileinput-button">
          <i class="icon-plus icon-white"></i>
          <span><%=t('.add_shots')%></span>
          <%= f.file_field :media %>
        </span>
        <button type="submit" class="btn btn-primary start">
          <i class="icon-upload icon-white"></i>
          <span><%=t('.start_upload')%></span>
        </button>
        <button type="reset" class="btn btn-warning cancel">
          <i class="icon-ban-circle icon-white"></i>
          <span><%=t('.cancel_upload')%></span>
        </button>
        <button type="button" class="btn btn-danger delete">
          <i class="icon-trash icon-white"></i>
          <span><%=t('.delete')%></span>
        </button>
        <input type="checkbox" class="toggle">
      </div>
      <div class="span5">
        <!-- The global progress bar -->
        <div class="progress progress-success progress-striped active fade">
          <div class="bar" style="width:0%;"></div>
        </div>
      </div>
    </div>
    <p>
        <%=link_to_modal t('.complete_upload'),crumbs_sorter_path,class:'btn btn-info' %>
      </p>
    <!-- The loading indicator is shown during image processing -->
    <div class="fileupload-loading"></div>
    <br>
    <!-- The table listing the files available for upload/download -->
    <table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
    </table>
  <% end %>

</div>
<script>
  var fileUploadErrors = {
  maxFileSize: 'File is too big',
  minFileSize: 'File is too small',
  acceptFileTypes: 'Filetype not allowed',
  maxNumberOfFiles: 'Max number of files exceeded',
  uploadedBytes: 'Uploaded bytes exceed file size',
  emptyResult: 'Empty file upload result'
  };
</script>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  <tr class="template-upload fade">
    <td class="preview"><span class="fade"></span></td>
    <td class="name"><span>{%=file.name%}</span></td>
    <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
    {% if (file.error) { %}
    <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
    {% } else if (o.files.valid && !i) { %}
    <td>
      <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
    </td>
    <td class="start">{% if (!o.options.autoUpload) { %}
      <button class="btn btn-primary">
        <i class="icon-upload icon-white"></i>
        <span>{%=locale.fileupload.start%}</span>
      </button>
      {% } %}</td>
    {% } else { %}
    <td colspan="2"></td>
    {% } %}
    <td class="cancel">{% if (!i) { %}
      <button class="btn btn-warning">
        <i class="icon-ban-circle icon-white"></i>
        <span>{%=locale.fileupload.cancel%}</span>
      </button>
      {% } %}</td>
  </tr>
  {% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
      {% if (file.error) { %}
        <td></td>
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else { %}
        <td class="preview">{% if (file.thumbnail_url) { %}
          <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
          {% } %}</td>
        <td class="name">
          <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
        </td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td colspan="2"></td>
        {% } %}
      <td class="delete">
        <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
          <i class="icon-trash icon-white"></i>
          <span>{%=locale.fileupload.destroy%}</span>
        </button>
        <input type="checkbox" name="delete" value="1">
      </td>
    </tr>
    {% } %}
</script>

<script type="text/javascript" charset="utf-8">
  $(function () {
      // Initialize the jQuery File Upload widget:
      $('#fileupload').fileupload();
      // 
      // Load existing files:
      $.getJSON($('#fileupload').prop('action'), function (files) {
        var fu = $('#fileupload').data('blueimpFileupload'), 
          template;
        fu._adjustMaxNumberOfFiles(-files.length);
        console.log(files);
        template = fu._renderDownload(files)
          .appendTo($('#fileupload .files'));
        // Force reflow:
        fu._reflow = fu._transition && template.length &&
          template[0].offsetWidth;
        template.addClass('in');
        $('#loading').remove();
      });
  });
</script>